sudo: false
services:
- docker
before_script:
- docker pull clux/magic-forest
script:
- docker run --rm -v $PWD:/volume -w /volume -t clux/magic-forest ./bench.sh
- docker run --rm -v $PWD:/volume -w /volume -t clux/magic-forest ./test.sh
notifications:
  email:
    on_success: change
    on_failure: always
